
package com.yu.jj.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldServiceImpl", targetNamespace = "http://impl.ws.jj.yu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.ws.jj.yu.com/", className = "com.yu.jj.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.ws.jj.yu.com/", className = "com.yu.jj.client.SayHelloResponse")
    @Action(input = "http://impl.ws.jj.yu.com/HelloWorldServiceImpl/sayHelloRequest", output = "http://impl.ws.jj.yu.com/HelloWorldServiceImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayBye", targetNamespace = "http://impl.ws.jj.yu.com/", className = "com.yu.jj.client.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "http://impl.ws.jj.yu.com/", className = "com.yu.jj.client.SayByeResponse")
    @Action(input = "http://impl.ws.jj.yu.com/HelloWorldServiceImpl/sayByeRequest", output = "http://impl.ws.jj.yu.com/HelloWorldServiceImpl/sayByeResponse")
    public String sayBye(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
